//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMojaApp1.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfMojaApp1.resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akcije.
        /// </summary>
        public static string Akcije {
            get {
                return ResourceManager.GetString("Akcije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivni proizvodi.
        /// </summary>
        public static string AktivniProizvodi {
            get {
                return ResourceManager.GetString("AktivniProizvodi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena (KM).
        /// </summary>
        public static string Cijena {
            get {
                return ResourceManager.GetString("Cijena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string Datum {
            get {
                return ResourceManager.GetString("Datum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobavljač.
        /// </summary>
        public static string Dobavljac {
            get {
                return ResourceManager.GetString("Dobavljac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string Dodaj {
            get {
                return ResourceManager.GetString("Dodaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj proizvod.
        /// </summary>
        public static string DodajProizvod {
            get {
                return ResourceManager.GetString("DodajProizvod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        public static string Engleski {
            get {
                return ResourceManager.GetString("Engleski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmijeni cijenu.
        /// </summary>
        public static string IzmijeniCijenu {
            get {
                return ResourceManager.GetString("IzmijeniCijenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        public static string Jezik {
            get {
                return ResourceManager.GetString("Jezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menadžer JMB.
        /// </summary>
        public static string Menadzer {
            get {
                return ResourceManager.GetString("Menadzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narudžbe.
        /// </summary>
        public static string Narudzbe {
            get {
                return ResourceManager.GetString("Narudzbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        public static string Naziv {
            get {
                return ResourceManager.GetString("Naziv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Očisti filter.
        /// </summary>
        public static string OcistiFilter {
            get {
                return ResourceManager.GetString("OcistiFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjavi se.
        /// </summary>
        public static string OdjaviSe {
            get {
                return ResourceManager.GetString("OdjaviSe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled racuna.
        /// </summary>
        public static string PregledRacuna {
            get {
                return ResourceManager.GetString("PregledRacuna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to « Prethodna.
        /// </summary>
        public static string Prethodna {
            get {
                return ResourceManager.GetString("Prethodna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraži po JMB.
        /// </summary>
        public static string PretraziPoJmb {
            get {
                return ResourceManager.GetString("PretraziPoJmb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra.
        /// </summary>
        public static string Sifra {
            get {
                return ResourceManager.GetString("Sifra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sledeća ».
        /// </summary>
        public static string Sledeca {
            get {
                return ResourceManager.GetString("Sledeca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srpski.
        /// </summary>
        public static string Srpski {
            get {
                return ResourceManager.GetString("Srpski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trgovac.
        /// </summary>
        public static string Trgovac {
            get {
                return ResourceManager.GetString("Trgovac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukloni.
        /// </summary>
        public static string Ukloni {
            get {
                return ResourceManager.GetString("Ukloni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrsta drveta.
        /// </summary>
        public static string VrstaDrveta {
            get {
                return ResourceManager.GetString("VrstaDrveta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrsta proizvoda.
        /// </summary>
        public static string VrstaProizvoda {
            get {
                return ResourceManager.GetString("VrstaProizvoda", resourceCulture);
            }
        }
    }
}
